seed: 42

dataset:
  name: RAFDB
  root: data/processed
  splits_dir: data/splits
  image_size: 128
  channels: 1
  train_split: train.csv
  val_split: val.csv
  test_split: test.csv

preprocessing:
  normalize:
    mean: [0.5]
    std: [0.5]
  use_hist_equalization: false

augmentation:
  horizontal_flip: true
  rotation_deg: 15
  translate: 0.1
  brightness: 0.2
  contrast: 0.2
  saturation: 0.0
  hue: 0.0
  random_erasing: true
  random_erasing_p: 0.5
  random_erasing_scale: [0.02, 0.33]
  random_erasing_ratio: [0.3, 3.3]

model:
  name: shallow_cnn        # <-- IMPORTANT
  in_channels: 1           
  num_classes: 7
  base_channels: 32        # shallow CNN uses 32 then 64
  use_depthwise: false     # shallow CNN is simple
  use_residual: false
  attention_type: "none"   # shallow = no attention
  activation: "relu"
  dropout_block: 0.1
  hidden_dim: 128          # simple FC layer
  dropout_head: 0.2

training:
  batch_size: 64
  num_epochs: 40           # shallow CNN entraîne beaucoup plus vite
  num_workers: 4
  pin_memory: true
  early_stopping_patience: 10

optimizer:
  name: adam
  lr: 0.001
  weight_decay: 0.0

scheduler:
  name: cosine_annealing
  T_max: 20
  eta_min: 1.0e-05

logging:
  log_dir: experiments/logs
  checkpoint_dir: experiments/checkpoints
  save_best_metric: val_macro_f1
  tensorboard: true
